server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # --- WASM MIME type ---
    types {
        application/wasm wasm;
    }

    # --- Surfer WASM needs these headers for SharedArrayBuffer ---
    location /surfer/ {
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        try_files $uri $uri/ =404;
    }


    location / {
        try_files $uri /index.html;
    }
}
